### ISSUE TITLE
cross-chain addresses

### ISSUE THREAD

**Issue by tzemanovic** [anoma/anoma-archive#284]
* Do we want to use the same addresses on different chains (fractal scaling, protocol upgrades) or distinguish them? 
* Would be better if an address from one chain is invalid on another chain?
* Are there any privacy concerns/considerations with distinguishing them?

We should consider whether we might want to use a schema similar to the [unified addresses proposed in Zcash](https://github.com/zcash/zips/issues/482), that are designed to unify the payment addresses across different versions by encoding a typecode and the length of the payment address together with it.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201757896515792/1201762883385866) by [Unito](https://www.unito.io)

**Comment by cwgoes** [comment]
Another related question is whether we want some form of hash-tied validity predicate address (like implicit addresses are public-key-tied, so they can be paid to before they have been used on the chain itself). Ideally we'd have a way for a user to create an address that (a) can be sent to before they have interacted with the ledger and (b) can result in the creation of a validity predicate account later sometime when the user does interact with the ledger.
