### ISSUE TITLE
Storage data sharing

### ISSUE THREAD

**Issue by tzemanovic** [anoma/anoma-archive#285]
Because we chose to separate the merkle tree from the data storage (and more specifically account storage sub-spaces), we don't have data sharing that is implied by merklelized storage. In some cases it would be preferable to store the data in shared space. 

For example, it should be fairly common that a lot of users' validity predicates are the same. Another example is the planned feature for data schema described in `data-schema.md`. 

Open questions:

* Do we want to enable data sharing for everything and anything (i.e. storing references via hash of the data to shared storage) or choose when to use it?
* Would it be useful to generalize this concept? It would be nice if Anoma users can also benefit from it
* How to deal with shared storage space rent fees? Does everyone pay fees as if there was no data sharing? It would be nice if we could reduce the fees, so that shared data that are very common become very cheap to use (this would be especially nice for the data schema).

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201757896515792/1201762935840694) by [Unito](https://www.unito.io)

**Comment by cwgoes** [comment]
If we can do automated sharing of e.g. validity predicate code via something like hash-consing, that would be quite nice. 

> Would it be useful to generalize this concept? It would be nice if Anoma users can also benefit from it

What specifically do you mean - who are users in this context? Users of some particular validity predicate?

**Comment by tzemanovic** [comment]
> What specifically do you mean - who are users in this context? Users of some particular validity predicate?

In this context, it’s the accounts and their sub-spaces. That is transactions would write some custom data that may be common to many accounts and understood by custom VPs
