### ISSUE TITLE
storage keys conflicts

### ISSUE THREAD

**Issue by tzemanovic** [anoma/anoma-archive#289]
We use specific storage key paths for common data types (e.g. public keys, token balances). It would be nice to come up with a way to prevent or at least warn against conflicts in user defined storage keys.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201757896515792/1201762883008055) by [Unito](https://www.unito.io)

**Comment by cwgoes** [comment]
I think this can't be enforced by the ledger, but it should definitely be standardised.
