### ISSUE TITLE
update matchmakers to receive existing intents from mempool when they connect to intent gossiper

### ISSUE THREAD

**Issue by sribst** [anoma/anoma-archive#348]
We need to change the entrypoint's interface to be able receive all intents on start-up, right? Currently, it only takes a single intent.

Another thing, because the matchmaker receives the last state and can update it, we'll need to have e.g. a queue of intents that is processed sequentially to avoid data races on the state.

_Originally posted by tzemanovic in https://github.com/anoma/anoma/pull/334#discussion_r670329037_

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201757896515792/1201762886768638) by [Unito](https://www.unito.io)

**Comment by tzemanovic** [comment]
The matchmaker is no longer in wasm and it is guaranteed to run from a single thread so there are no data races (it can spawn more threads itself, but then it's ofc the responsibility of the implementor to handle the state).

We should update the matchmakers to receive all the relevant intents that haven't timed out from mempool when they connect to the intent gossiper.
