### ISSUE TITLE
Quick install command for non-production situations

### ISSUE THREAD

**Issue by cwgoes** [anoma/anoma-archive#578]
As a tester of the Anoma node, client, etc. in testnets, I'd like the ability to build Anoma quickly (if this comes with some performance costs, that's fine) so that I can get started testing without waiting so long. Could there be an option to `make install-dev` or something like that to install a development (or less-optimised) build that would complete faster (ideally within a minute or so)?

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201757896515792/1201763123484479) by [Unito](https://www.unito.io)

**Comment by tzemanovic** [comment]
The "dev" has been switched off by default in #595, the new command is just `cargo install --path ./apps --debug`
