### ISSUE TITLE
Allow non-synced nodes to process and forward transactions

### ISSUE THREAD

**Issue by adrianbrink** [anoma/anoma-archive#793]
It would be great if a node that isn't fully synced yet can nevertheless receive transactions and forward them to its peers. It would make the UX a bit nicer.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201757896515792/1201762914846093) by [Unito](https://www.unito.io)

**Comment by cwgoes** [comment]
Hmm, it doesn't have the latest state though, so how can it run `CheckTx`?

**Comment by adrianbrink** [comment]
Better UX. Since nodes should expect to receive garbage (as in they need to be spam resistant on the P2P layer), I think we should be able to forward without having run `CheckTx` as long as it comes from a local RPC submission.

**Comment by cwgoes** [comment]
Ah, I see. In that case I think this is reasonable, though it may require forking Tendermint, which is annoying :/ .
